version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile.prod
    container_name: api
    tty: true
    volumes:
      - .:/home/python/app
      - ./logs:/logs
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    container_name: frontend
    tty: true
    volumes:
      - ./frontend:/home/ui
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - api
