version: '3'

services:
  api:
    build: .
    container_name: api
    command: ./.docker/entrypoint.sh
    tty: true
    volumes:
      - .:/home/python/app
      - ./logs:/logs
    ports:
      - 8000:8000
    networks:
      - my-users-network
  
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    command: .docker/entrypoint.sh
    tty: true
    volumes:
      - ./frontend:/home/ui
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - my-users-network
  
networks:
  my-users-network:
    driver: bridge
  
    


